/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '18-1-9 下午8:55' with Gradle 2.11
 *
 * @author Administrator, @date 18-1-9 下午8:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
